### ISSUE TITLE
[Bug] Crash on Randomize, NoClassFoundError

### ISSUE THREAD

**Issue by cjtonner** [upr-fvx/universal-pokemon-randomizer-fvx#17]
**Describe the bug**
When randomizing, an exception occurs, causing the randomizer to freeze and fail to generate the file.

**To Reproduce**
1. Load Platinum (U Rev 1)
2. Use included randomization configuration.
3. Randomize (Save)

**Expected behavior**
A file is generated, in addition to optinal log file, etc.

**System (please complete the following information):**
 - Operating System: Windows 10
 - Java Version: 17.0.6
 - Randomizer Version: 1.0.3

**Additional context**
Have randomized other games recently perfectly fine. Only major setting difference this time would be using randomized palettes. Also, apologies, but I couldn't find the log, so I've included a text file of the console output.
[crashlog 2024-11-04.txt](https://github.com/user-attachments/files/17616987/crashlog.2024-11-04.txt)

**Comment by foxoftheasterisk** [comment]
Oh, that is funky.

As best I can tell it's due to you using too _new_ a version of Java—apparently they're not fully backwards compatible. What I don't understand is why this only occurred now. Is this the first time you've used the "Keep Evolutions" option for wild Pokemon?

Anyway, you should be able to work around it by downloading Java 8 (and, probably, setting it as default). I'll also amend the code so this shouldn't happen in future releases.

**Comment by cjtonner** [comment]
First, whoops, I meant to include my settings file, oh well. But yeah, just tested a default config except for random wild and keep evos, which crashed, and my full config MINUS keep evolution, and it generated fine. I thought I had used keep evos before, but maybe not. Thanks though.
